global:
  scrape_interval: 15s  # Intervalo de coleta de métricas

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['healthgateway_api:8080'] # 🔹 Porta do Ocelot

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
